SELECT T.ID_TRAJET, RETARD_DEPART, RETARD_ARRIVEE, N.PROPRETE
FROM TRAJET T
JOIN NEW_CLIENT NC ON T.ID_CLIENT = NC.ID_NEW_CLIENT
JOIN NOTES N ON ID_FORMS = N.ID_FORMS
WHERE NC.AGE < 30 AND N.PROPRETE > (SELECT AVG(PROPRETE) FROM NOTES);